-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 09:08:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema car
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car` DEFAULT CHARACTER SET utf8 ;
USE `car` ;

-- -----------------------------------------------------
-- Table `car`.`Offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`Offices` (
  `idOffices` INT(10) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(20) NOT NULL,
  `addressLine1` VARCHAR(45) NOT NULL,
  `addressLine2` VARCHAR(45) NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idOffices`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`Employees` (
  `idEmployees` INT NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `jobTitle` VARCHAR(45) NOT NULL,
  `Offices_idOffices` INT NOT NULL,
  `Employees_idEmployees` INT NOT NULL,
  `Employees_Offices_idOffices` INT NOT NULL,
  PRIMARY KEY (`idEmployees`, `Offices_idOffices`, `Employees_idEmployees`, `Employees_Offices_idOffices`),
  INDEX `fk_Employees_Offices1_idx` (`Offices_idOffices` ASC) VISIBLE,
  INDEX `fk_Employees_Employees1_idx` (`Employees_idEmployees` ASC, `Employees_Offices_idOffices` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Offices1`
    FOREIGN KEY (`Offices_idOffices`)
    REFERENCES `car`.`Offices` (`idOffices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_Employees1`
    FOREIGN KEY (`Employees_idEmployees` , `Employees_Offices_idOffices`)
    REFERENCES `car`.`Employees` (`idEmployees` , `Offices_idOffices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`Customers` (
  `idCustomers` INT NOT NULL  auto_increment,
  `nameCustomer` VARCHAR(45) NOT NULL,
  `contactLastName` VARCHAR(45) NOT NULL,
  `contactFirstName` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(20) NOT NULL,
  `addressLine1` VARCHAR(50) NOT NULL DEFAULT 'Hue city',
  `addressLine2` VARCHAR(50) NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(15) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `creditLimit` DOUBLE NULL,
  `Employees_idEmployees` INT NOT NULL,
  PRIMARY KEY (`idCustomers`, `Employees_idEmployees`),
  INDEX `fk_Customers_Employees1_idx` (`Employees_idEmployees` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Employees1`
    FOREIGN KEY (`Employees_idEmployees`)
    REFERENCES `car`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car`.`ProductsLine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`ProductsLine` (
  `idProductsLine` INT NOT NULL,
  `textDescription` TEXT NULL DEFAULT 'normal',
  `image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idProductsLine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`Products` (
  `idProducts` INT NOT NULL,
  `productName` VARCHAR(70) NOT NULL,
  `productScale` VARCHAR(10) NOT NULL,
  `productVendor` VARCHAR(45) NOT NULL,
  `productDescription` TEXT NULL,
  `quantityInStock` INT NOT NULL,
  `buyPrice` DOUBLE NOT NULL DEFAULT buyPrice > 0,
  `MSRP` DOUBLE NOT NULL DEFAULT MSRP > 0,
  `ProductsLine_idProductsLine` INT NOT NULL,
  PRIMARY KEY (`idProducts`, `ProductsLine_idProductsLine`),
  INDEX `fk_Products_ProductsLine1_idx` (`ProductsLine_idProductsLine` ASC) VISIBLE,
  CONSTRAINT `fk_Products_ProductsLine1`
    FOREIGN KEY (`ProductsLine_idProductsLine`)
    REFERENCES `car`.`ProductsLine` (`idProductsLine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`Orders` (
  `idOrders` INT NOT NULL,
  `orderDate` DATE NOT NULL,
  `requiredDate` DATE NOT NULL,
  `shippedDate` DATE NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `comments` TEXT NULL,
  `quantityOrdered` INT NOT NULL,
  `priceEach` DOUBLE NOT NULL DEFAULT priceEach > 0,
  `Customers_idCustomers` INT NOT NULL,
  PRIMARY KEY (`idOrders`, `Customers_idCustomers`),
  INDEX `fk_Orders_Customers_idx` (`Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customers`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `car`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`Payments` (
  `idPayments` INT NOT NULL,
  `checkNumber` VARCHAR(45) NOT NULL,
  `paymentDate` DATE NOT NULL,
  `amount` DOUBLE NOT NULL DEFAULT amount > 0,
  `Customers_idCustomers` INT NOT NULL,
  PRIMARY KEY (`idPayments`, `Customers_idCustomers`),
  INDEX `fk_Payments_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Payments_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `car`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car`.`OrderDetails` (
  `Products_idProducts` INT NOT NULL,
  `Orders_idOrders` INT NOT NULL,
  `Orders_Customers_idCustomers` INT NOT NULL,
  PRIMARY KEY (`Products_idProducts`, `Orders_idOrders`, `Orders_Customers_idCustomers`),
  INDEX `fk_Products_has_Orders_Orders1_idx` (`Orders_idOrders` ASC, `Orders_Customers_idCustomers` ASC) VISIBLE,
  INDEX `fk_Products_has_Orders_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Orders_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `car`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Orders_Orders1`
    FOREIGN KEY (`Orders_idOrders` , `Orders_Customers_idCustomers`)
    REFERENCES `car`.`Orders` (`idOrders` , `Customers_idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
